{% set name = "sos-julia" %}
{% set version = "0.18.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2c67e0d18f54eaeebaaf11537b03d753206711debaf04c7c1673ecd3ae962bc

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.7
    - jupyter_contrib_core
  run:
    - sos-notebook >=0.22.6
    - feather-format
    - python >=3.7
    - jupyter_contrib_core
    - jupyter_contrib_nbextensions    

test:
  requires:
    - nose
    - pytest
    - selenium
    - jupyter_contrib_core
    - jupyter_contrib_nbextensions
    - sos-notebook >=0.22.6
  imports:
    - sos_julia

about:
  home: https://github.com/vatlab/sos-julia
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SoS language module for Julia
  doc_url: https://vatlab.github.io/sos-docs/
  dev_url: https://github.com/vatlab/sos-julia

extra:
  recipe-maintainers:
    - BoPeng
